In [1]:
from stock_dataset import *

In [2]:
minibatch_producer(timeseries_length=1, minibatch_size=1, num_companies=1)()

array([[[[2.620800e+02, 2.674900e+02, 2.667400e+02, 2.631400e+02,
          2.020863e+06]]]])

In [3]:
concat_data(read_time_series(timeseries_length=2))

,Symbol,Date,Low.0,High.0,Open.0,Close.0,Volume.0,Low.1,High.1,Open.1,Close.1,Volume.1
0,AAPL,2013-01-03,69.978,71.705,71.553,70.935,154865509,69.896,71.017,70.745,70.039,97488400
1,AAPL,2013-01-04,69.896,71.017,70.745,70.039,97488400,67.936,69.591,69.375,68.088,164191192
2,AAPL,2013-01-07,67.936,69.591,69.375,68.088,164191192,66.566,68.386,67.446,67.689,133721724
3,AAPL,2013-01-08,66.566,68.386,67.446,67.689,133721724,67.346,68.721,68.375,67.871,126651168
4,AAPL,2013-01-09,67.346,68.721,68.375,67.871,126651168,66.664,67.830,67.533,66.808,112611881
5,AAPL,2013-01-10,66.664,67.830,67.533,66.808,112611881,66.607,68.310,68.287,67.636,166038770
6,AAPL,2013-01-11,66.607,68.310,68.287,67.636,166038770,67.057,67.872,67.331,67.222,96900287
7,AAPL,2013-01-14,67.057,67.872,67.331,67.222,96900287,64.407,65.568,64.945,64.827,202815867
8,AAPL,2013-01-15,64.407,65.568,64.945,64.827,202815867,62.452,64.470,64.382,62.781,242045402
9,AAPL,2013-01-16,62.452,64.470,64.382,62.781,242045402,63.630,65.820,63.907,65.383,190827569
10,AAPL,2013-01-17,63.630,65.820,63.907,65.383,190827569,64.862,65.990,65.931,64.945,125178052
11,AAPL,2013-01-18,64.862,65.990,65.931,64.945,125178052,64.133,64.887,64.407,64.601,130744810
12,AAPL,2013-01-22,64.133,64.887,64.407,64.601,130744810,64.165,65.617,65.188,65.216,127334286
13,AAPL,2013-01-23,64.165,65.617,65.188,65.216,127334286,65.216,66.537,65.739,66.411,237111514
14,AAPL,2013-01-24,65.216,66.537,65.739,66.411,237111514,58.170,60.171,59.431,58.204,403617999
15,AAPL,2013-01-25,58.170,60.171,59.431,58.204,403617999,56.203,58.944,58.359,56.834,333813084
16,AAPL,2013-01-28,56.203,58.944,58.359,56.834,333813084,56.313,58.556,56.566,58.120,216935263
17,AAPL,2013-01-29,56.313,58.556,56.566,58.120,216935263,58.413,59.458,59.238,59.208,157788647
18,AAPL,2013-01-30,58.413,59.458,59.238,59.208,157788647,58.721,59.766,59.044,59.022,115265298
19,AAPL,2013-01-31,58.721,59.766,59.044,59.022,115265298,58.783,59.339,59.041,58.846,88226409
20,AAPL,2013-02-01,58.783,59.339,59.041,58.846,88226409,57.926,59.365,59.317,58.607,149077967
21,AAPL,2013-02-04,57.926,59.365,59.317,58.607,149077967,57.107,58.907,58.644,57.148,131820063
22,AAPL,2013-02-05,57.107,58.907,58.644,57.148,131820063,57.135,59.398,57.370,59.151,158410285
23,AAPL,2013-02-06,57.135,59.398,57.370,59.151,158410285,58.473,60.271,58.975,59.090,163969146
24,AAPL,2013-02-07,58.473,60.271,58.975,59.090,163969146,59.014,61.076,60.203,60.845,193075926
25,AAPL,2013-02-08,59.014,61.076,60.203,60.845,193075926,60.849,62.222,61.597,61.725,173919690
26,AAPL,2013-02-11,60.849,62.222,61.597,61.725,173919690,61.501,63.017,61.921,62.369,142116427
27,AAPL,2013-02-12,61.501,63.017,61.921,62.369,142116427,60.784,62.688,62.313,60.804,167111380
28,AAPL,2013-02-13,60.784,62.688,62.313,60.804,167111380,60.198,61.548,60.716,60.689,130528184
29,AAPL,2013-02-14,60.198,61.548,60.716,60.689,130528184,60.301,61.289,60.365,60.634,97666569
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,TSLA,2017-10-02,338.601,344.680,341.860,341.020,5099112,335.510,343.700,342.520,341.530,5243618
1196,TSLA,2017-10-03,335.510,343.700,342.520,341.530,5243618,331.280,348.550,335.900,348.140,10126541
1197,TSLA,2017-10-04,331.280,348.550,335.900,348.140,10126541,349.600,358.620,351.250,355.010,8148594
1198,TSLA,2017-10-05,349.600,358.620,351.250,355.010,8148594,351.350,357.435,356.000,355.140,4168161
1199,TSLA,2017-10-06,351.350,357.435,356.000,355.140,4168161,352.250,360.099,353.100,356.834,4277878
1200,TSLA,2017-10-09,352.250,360.099,353.100,356.834,4277878,342.670,351.750,349.650,342.940,7464351
1201,TSLA,2017-10-10,342.670,351.750,349.650,342.940,7464351,345.531,355.630,346.800,355.590,6972552
1202,TSLA,2017-10-11,345.531,355.630,346.800,355.590,6972552,351.150,357.600,353.890,354.600,4495328
1203,TSLA,2017-10-12,351.150,357.600,353.890,354.600,4495328,352.640,359.780,352.950,355.680,4075519
1204,TSLA,2017-10-13,352.640,359.780,352.950,355.680,4075519,353.680,358.490,356.980,355.570,3538958
1205,TSLA,2017-10-16,353.680,358.490,356.980,355.570,3538958,347.160,354.480,353.760,350.600,5373410
1206,TSLA,2017-10-17,347.160,354.480,353.760,350.600,5373410,350.070,356.220,350.910,355.750,3290317
1207,TSLA,2017-10-18,350.070,356.220,350.910,355.750,3290317,354.130,363.000,355.970,359.650,4936166
1208,TSLA,2017-10-19,354.130,363.000,355.970,359.650,4936166,348.200,357.147,355.560,351.810,5056722
1209,TSLA,2017-10-20,348.200,357.147,355.560,351.810,5056722,344.340,354.550,352.690,345.100,4926667
1210,TSLA,2017-10-23,344.340,354.550,352.690,345.100,4926667,336.250,349.950,349.880,337.020,5740366
1211,TSLA,2017-10-24,336.250,349.950,349.880,337.020,5740366,336.160,342.800,338.800,337.340,4488426
1212,TSLA,2017-10-25,336.160,342.800,338.800,337.340,4488426,323.560,337.500,336.700,325.840,8584204
1213,TSLA,2017-10-26,323.560,337.500,336.700,325.840,8584204,323.200,330.230,327.780,326.170,5012087
1214,TSLA,2017-10-27,323.200,330.230,327.780,326.170,5012087,316.660,324.590,319.750,320.870,6970118
1215,TSLA,2017-10-30,316.660,324.590,319.750,320.870,6970118,317.250,323.780,319.180,320.080,4254378
1216,TSLA,2017-10-31,317.250,323.780,319.180,320.080,4254378,320.180,331.950,320.230,331.530,5672347
1217,TSLA,2017-11-01,320.180,331.950,320.230,331.530,5672347,320.260,332.609,332.250,321.080,8457336
1218,TSLA,2017-11-02,320.260,332.609,332.250,321.080,8457336,292.630,308.690,300.130,299.260,19791416
1219,TSLA,2017-11-03,292.630,308.690,300.130,299.260,19791416,295.130,306.250,299.500,306.090,8893974
1220,TSLA,2017-11-06,295.130,306.250,299.500,306.090,8893974,299.010,307.500,307.000,302.780,6482486
1221,TSLA,2017-11-07,299.010,307.500,307.000,302.780,6482486,300.030,306.500,301.020,306.050,5286320
1222,TSLA,2017-11-08,300.030,306.500,301.020,306.050,5286320,301.300,306.890,305.500,304.310,4725510
1223,TSLA,2017-11-09,301.300,306.890,305.500,304.310,4725510,296.300,304.460,302.500,302.990,5440335
1224,TSLA,2017-11-10,296.300,304.460,302.500,302.990,5440335,301.850,308.360,302.500,302.990,4621912